name: celery-collectors
channels:
  - nodefaults
  - conda-forge
dependencies:
  - celery
  - flower
  - python 3.10.*
  - pip:
    - rabbitmq
    - redis
    - pytest
    - pytest-celery 
    - factory_boy
    - pytest-asyncio
